---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-test-kateops-com-v1-operatortest
  failurePolicy: Fail
  name: moperatortest.kb.io
  rules:
  - apiGroups:
    - crd.test.kateops.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operatortests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-test-kateops-com-v1-operatortest
  failurePolicy: Fail
  name: voperatortest.kb.io
  rules:
  - apiGroups:
    - crd.test.kateops.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - operatortests
  sideEffects: None
