---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - crd.test.kateops.com
  resources:
  - observers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.test.kateops.com
  resources:
  - observers/finalizers
  verbs:
  - update
- apiGroups:
  - crd.test.kateops.com
  resources:
  - observers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.test.kateops.com
  resources:
  - operatortests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.test.kateops.com
  resources:
  - operatortests/finalizers
  verbs:
  - update
- apiGroups:
  - crd.test.kateops.com
  resources:
  - operatortests/status
  verbs:
  - get
  - patch
  - update
