
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: derhauck/operator-test
          registry: ghcr.io
          enableBuildKit: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}